import type { Metadata } from "next";
import "./globals.css";
import { sans_serif } from "./fonts";
import Navbar from "./components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sans_serif.className}  antialiased`}>
        <nav>
          <Navbar />
        </nav>{" "}
        {children}
      </body>
    </html>
  );
}
